/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewfavouriteImport } from './routes/newfavourite'
import { Route as FavouritesImport } from './routes/favourites'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NewfavouriteRoute = NewfavouriteImport.update({
  id: '/newfavourite',
  path: '/newfavourite',
  getParentRoute: () => rootRoute,
} as any)

const FavouritesRoute = FavouritesImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesImport
      parentRoute: typeof rootRoute
    }
    '/newfavourite': {
      id: '/newfavourite'
      path: '/newfavourite'
      fullPath: '/newfavourite'
      preLoaderRoute: typeof NewfavouriteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/newfavourite': typeof NewfavouriteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/newfavourite': typeof NewfavouriteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/newfavourite': typeof NewfavouriteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favourites' | '/newfavourite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favourites' | '/newfavourite'
  id: '__root__' | '/' | '/favourites' | '/newfavourite'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  NewfavouriteRoute: typeof NewfavouriteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  NewfavouriteRoute: NewfavouriteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/favourites",
        "/newfavourite"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/favourites": {
      "filePath": "favourites.tsx"
    },
    "/newfavourite": {
      "filePath": "newfavourite.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
